-- COUNT NUMBER OF STUDENTS IN EACH BATCH
SELECT BATCH, COUNT(BATCH) AS NO_OF_STDS FROM Student
GROUP BY BATCH

-- TOTAL NO OF BOOKS ISSUED
SELECT COUNT(bid) AS TOTAL_BOOKS_ISSUED FROM issues

-- BATCHES HAVING MORE THAN 5 STUDENTS
SELECT BATCH FROM Student 
GROUP BY BATCH
HAVING COUNT(BATCH)>5

-- 
SELECT * FROM Student